package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Justin
 */
public class Menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnParticipantes = new javax.swing.JButton();
        btnHistorias = new javax.swing.JButton();
        btnScrumPoker = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("SCRUM POKER");

        btnParticipantes.setText("PARTICIPANTES");

        btnHistorias.setText("HISTORIAS DE USUARIO");

        btnScrumPoker.setText("SCRUM POKER");

        btnSalir.setText("SALIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHistorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnScrumPoker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblTitulo)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addGap(37, 37, 37)
                .addComponent(btnParticipantes)
                .addGap(18, 18, 18)
                .addComponent(btnHistorias)
                .addGap(18, 18, 18)
                .addComponent(btnScrumPoker)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorias;
    private javax.swing.JButton btnParticipantes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnScrumPoker;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    // GETTERS Y SETTERS
    public javax.swing.JButton getBtnParticipantes() {
        return btnParticipantes;
    }

    public void setBtnParticipantes(javax.swing.JButton btnParticipantes) {
        this.btnParticipantes = btnParticipantes;
    }

    public javax.swing.JButton getBtnHistorias() {
        return btnHistorias;
    }

    public void setBtnHistorias(javax.swing.JButton btnHistorias) {
        this.btnHistorias = btnHistorias;
    }

    public javax.swing.JButton getBtnScrumPoker() {
        return btnScrumPoker;
    }

    public void setBtnScrumPoker(javax.swing.JButton btnScrumPoker) {
        this.btnScrumPoker = btnScrumPoker;
    }

    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(javax.swing.JButton btnSalir) {
        this.btnSalir = btnSalir;
    }
}
