/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Justin
 */
public class ScrumPoker extends javax.swing.JFrame {

    /**
     * Creates new form ScrumPoker
     */
    public ScrumPoker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblHistoria = new javax.swing.JLabel();
        lblDesarrollador = new javax.swing.JLabel();
        lblPunto = new javax.swing.JLabel();
        cmbHistoria = new javax.swing.JComboBox<>();
        cmbDesarrollador = new javax.swing.JComboBox<>();
        cmbPunto = new javax.swing.JComboBox<>();
        btnVotar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        txtEstimacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVotos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setText("SCRUM POKER");

        lblHistoria.setText("Historia:");

        lblDesarrollador.setText("Desarrollador:");

        lblPunto.setText("Punto:");

        cmbHistoria.setModel(new javax.swing.DefaultComboBoxModel<modelo.HistoriaUsuario>());

        cmbDesarrollador.setModel(new javax.swing.DefaultComboBoxModel<modelo.Desarrollador>());

        cmbPunto.setModel(new javax.swing.DefaultComboBoxModel<modelo.PuntoEstimacion>());

        btnVotar.setText("VOTAR");

        jLabel5.setText("VOTOS REGISTRADOS");

        btnConsultar.setText("CONSULTAR VOTOS");

        btnCalcular.setText("CALCULAR ESTIMACIÓN");

        lblResultado.setText("Resultado:");

        tblVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Desarrollador", "Historia", "Puntos"
            }
        ));
        jScrollPane1.setViewportView(tblVotos);

        btnVolver.setText("VOLVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPunto)
                                .addGap(55, 55, 55)
                                .addComponent(cmbPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDesarrollador)
                                    .addComponent(lblHistoria))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblResultado)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstimacion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHistoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesarrollador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPunto))
                .addGap(31, 31, 31)
                .addComponent(btnVotar)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnCalcular))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtEstimacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVotar;
    private javax.swing.JComboBox<modelo.Desarrollador> cmbDesarrollador;
    private javax.swing.JComboBox<modelo.HistoriaUsuario> cmbHistoria;
    private javax.swing.JComboBox<modelo.PuntoEstimacion> cmbPunto;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesarrollador;
    private javax.swing.JLabel lblHistoria;
    private javax.swing.JLabel lblPunto;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblVotos;
    private javax.swing.JTextField txtEstimacion;
    // End of variables declaration//GEN-END:variables

    // GETTERS Y SETTERS
    public javax.swing.JComboBox<modelo.HistoriaUsuario> getCmbHistoria() {
        return cmbHistoria;
    }

    public void setCmbHistoria(javax.swing.JComboBox<modelo.HistoriaUsuario> valor) {
        cmbHistoria = valor;
    }

    public javax.swing.JComboBox<modelo.Desarrollador> getCmbDesarrollador() {
        return cmbDesarrollador;
    }

    public void setCmbDesarrollador(javax.swing.JComboBox<modelo.Desarrollador> valor) {
        cmbDesarrollador = valor;
    }

    public javax.swing.JComboBox<modelo.PuntoEstimacion> getCmbPunto() {
        return cmbPunto;
    }

    public void setCmbPunto(javax.swing.JComboBox<modelo.PuntoEstimacion> valor) {
        cmbPunto = valor;
    }

    public javax.swing.JButton getBtnVotar() {
        return btnVotar;
    }

    public void setBtnVotar(javax.swing.JButton valor) {
        btnVotar = valor;
    }

    public javax.swing.JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(javax.swing.JButton valor) {
        btnConsultar = valor;
    }

    public javax.swing.JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(javax.swing.JButton valor) {
        btnCalcular = valor;
    }

    public javax.swing.JTable getTblVotos() {
        return tblVotos;
    }

    public void setTblVotos(javax.swing.JTable valor) {
        tblVotos = valor;
    }

    public String getTxtEstimacion() {
        return txtEstimacion.getText();
    }

    public void setTxtEstimacion(String valor) {
        txtEstimacion.setText(valor);
    }

    public javax.swing.JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(javax.swing.JButton btnVolver) {
        this.btnVolver = btnVolver;
    }
}
